[PR] # PR Sketch

  [PR.para]
  counter_length = 161000
  filter_length = 1136784
  counter_hash_num = 4
  filter_hash_num = 5
  phi = 10

  [PR.data]
  cnt_method = "InPacket"
  data = "../data/records.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [PR.test]
  update = []
  query = ["ARE", "PODF"]
  query_podf = 0.001
