[NZE] # NZE

  [NZE.para]
  BFHashNum = 5
  BFBitsNum = 316448
  FSdepth = 3
  FSwidth = 10
  HTLength = 4300

  [NZE.data]
  cnt_method = "InPacket"
  data = "../data/records.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [NZE.test]
  update = []
  query = ["ARE", "PODF"]
  query_podf = 0.001