[ES] # Elastic Sketch

  [ES.para]
  num_buckets = 80
  num_per_bucket = 1
  l_depth = 2
  l_width = 60957

  [ES.data]
  cnt_method = "InPacket"
  data = "../data/records.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [ES.test]
  update = []
  query = ["ARE", "PODF"]
  query_podf = 0.001

  [ES.bs]
  cnt_no_ratio = 0.1
  width_cnt = [14, 4]
  no_hash = [3]
  cm_cnt_no_ratio = 0.1
  cm_width_cnt = [6, 12]
  cm_no_hash = [3]
  heavy_cm_r = 3
  heavy_cm_w = 500