[FlowRadar] # Flow Radar

  [FlowRadar.para]
    count_table_num = 17800
    count_table_hash = 1
    flow_filter_hash = 10
    flow_filter_bit = 151744
  
  [FlowRadar.data]
    data = "../data/records.bin"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
  
  [FlowRadar.test]
    update = []
    decode = ["ARE", "PODF", "RATIO"]
    decode_podf = 0.001