[NZE] # NZE

  [NZE.para]
  BFHashNum = 5
  BFBitsNum = 923088
  FSdepth = 7
  FSwidth = 14700
  HTLength = 14800

  [NZE.data]
  cnt_method = "InPacket"
  data = "../data/records.bin"
  format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]

  [NZE.test]
  update = []
  query = ["ARE", "PODF"]
  query_podf = 0.001

  [NZE.bs]
  cnt_no_ratio = 0.1
  width_cnt = [5, 14]
  no_hash = [3]