[UM] # UnivMon

  [UM.para]
    depth = 1
    width = 960152
  
  [UM.data]
    data = "../data/records.bin"
    format = [["flowkey", "padding", "timestamp", "length", "padding"], [13, 3, 8, 2, 6]]
    cnt_method = "InPacket"

  [UM.test]
    update = []
    query = ["ARE", "PODF"]
    query_podf = 0.001
  
  [UM.bs]
    cnt_no_ratio = 0.085
    width_cnt = [2, 15]
    no_hash = [3]